options:
  ldap-url:
    type: string
    default: 
    description: "A short description of the configuration option"
  ldap-user:
    type: string
    default: 
    description: "A short description of the configuration option"
  ldap-password:
    type: string
    default: 
    description: "A short description of the configuration option"
  ldap-suffix:
    type: string
    default: 
    description: "A short description of the configuration option"

