options:
  ldap-url:
    type: string
    default: "ldap://localhost"
    description: "A short description of the configuration option"
  ldap-user:
    type: string
    default: "dc=Manager,dc=example,dc=org"
    description: "A short description of the configuration option"
  ldap-password:
    type: string
    default: "samplepassword"
    description: "A short description of the configuration option"
  ldap-suffix:
    type: string
    default: "dc=example,dc=org"
    description: "A short description of the configuration option"

